spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing:
  database: sql