spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: memory
  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    root: INFO
    pl:
      futurecollars:
        invoicing: DEBUG
