spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
invoicing:
  database: file
  database.directory: invoicing
  database.file: invoices.txt
  database.idFile: id.txt
logging:
  level:
    root: INFO
    pl:
      futurecollars:
        invoicing: DEBUG