package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Entity;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Data
@AllArgsConstructor
@Builder
@Entity
public class Car {

    @Id
    @JsonIgnore
    @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
    private int id;

    @ApiModelProperty(value = "is the car also for personal user")
    private boolean includingPersonalUse;

    @ApiModelProperty(value = "Registration number", example = "WX 333455")
    private String registration;
}
